
#include "headers/gpio.h"


uint32_t gpio_pins[] = {
		0x0,0x0,0x0,0x0,0x0,
		GPIO_OFFSET_PIN5,
		GPIO_OFFSET_PIN6,
		GPIO_OFFSET_PIN7,
		GPIO_OFFSET_PIN8,
		GPIO_OFFSET_PIN9,
		GPIO_OFFSET_PIN10,
		GPIO_OFFSET_PIN11,
		GPIO_OFFSET_PIN12,
		GPIO_OFFSET_PIN13,
		GPIO_OFFSET_PIN14,
		GPIO_OFFSET_PIN15,
		GPIO_OFFSET_PIN16,
		GPIO_OFFSET_PIN17,
		GPIO_OFFSET_PIN18,
		GPIO_OFFSET_PIN19,
		GPIO_OFFSET_PIN20,
		GPIO_OFFSET_PIN21,
		GPIO_OFFSET_PIN22,
		GPIO_OFFSET_PIN23,
		GPIO_OFFSET_PIN24,
		GPIO_OFFSET_PIN25,
		GPIO_OFFSET_PIN26
};